# Generated by Django 3.2.22 on 2024-07-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_produit_cree_le'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='etat',
            field=models.CharField(choices=[('neuf', 'Neuf'), ('casi_neuf', 'Casi neuf'), ('usage', "D'occasion"), ('pour_pieces', 'Pour pièces')], max_length=50),
        ),
    ]
