# Generated by Django 4.2 on 2024-11-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_produit_etat"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="qte_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
