# Generated by Django 6.0.1 on 2026-01-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_produit_qte_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
    ]
