# Generated by Django 3.2.22 on 2024-08-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom_boutique',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_cni_recto',
            field=models.ImageField(blank=True, null=True, upload_to='photos_cni_recto/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_cni_verso',
            field=models.ImageField(blank=True, null=True, upload_to='photos_cni_verso/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', related_query_name='utilisateur', to='auth.Group', verbose_name='groupes'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', related_query_name='utilisateur', to='auth.Permission', verbose_name='permissions utilisateur'),
        ),
    ]
