# Generated by Django 6.0.1 on 2026-01-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
