# Generated by Django 3.2.22 on 2024-06-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='users.utilisateur'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='orders.commande'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='noteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_attribuees', to='users.utilisateur'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='acheteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_en_tant_qu_acheteur', to='users.utilisateur'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='products.produit'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_en_tant_qu_vendeur', to='users.utilisateur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='acheteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_passees', to='users.utilisateur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='products.produit'),
        ),
    ]
