# Generated by Django 4.2 on 2024-10-25 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0003_commande_quantite"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="date_annulee",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commande",
            name="date_en_traitement",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commande",
            name="date_livraison",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commande",
            name="date_livree",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="commande",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("en_traitement", "En traitement"),
                    ("livraison_en_cours", "Livraison en cours"),
                    ("livree", "Livrée"),
                    ("annulee", "Annulée"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="HistoriqueStatutCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_traitement", "En traitement"),
                            ("livraison_en_cours", "Livraison en cours"),
                            ("livree", "Livrée"),
                            ("annulee", "Annulée"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_changement", models.DateTimeField(auto_now_add=True)),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_statuts",
                        to="orders.commande",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_changement"],
            },
        ),
    ]
